# Generated by Django 2.0.5 on 2018-10-24 23:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20181024_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 10, 24, 23, 12, 59, 11547, tzinfo=utc)),
        ),
    ]
