# Generated by Django 2.0.5 on 2018-10-25 16:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20181024_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 10, 25, 16, 33, 3, 659672, tzinfo=utc)),
        ),
    ]
