# Generated by Django 2.0 on 2018-10-26 07:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_auto_20181025_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 10, 26, 7, 6, 3, 712658, tzinfo=utc)),
        ),
    ]
