# Generated by Django 2.0 on 2018-10-26 07:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0018_auto_20181026_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 10, 26, 7, 12, 40, 282461, tzinfo=utc)),
        ),
    ]
