# Generated by Django 2.0.5 on 2018-10-28 00:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_auto_20181026_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 10, 28, 0, 18, 58, 769652, tzinfo=utc)),
        ),
    ]
