# Generated by Django 2.0.5 on 2018-10-28 05:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0023_auto_20181028_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 10, 28, 5, 36, 15, 906501, tzinfo=utc)),
        ),
    ]
