# Generated by Django 2.0 on 2018-11-02 22:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0026_auto_20181103_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 11, 2, 22, 55, 27, 789075, tzinfo=utc)),
        ),
    ]
