# Generated by Django 2.0 on 2018-11-03 00:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0027_auto_20181103_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 11, 3, 0, 30, 7, 868654, tzinfo=utc)),
        ),
    ]
