# Generated by Django 2.0 on 2018-11-03 01:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0028_auto_20181103_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2018, 11, 3, 1, 22, 37, 889436, tzinfo=utc)),
        ),
    ]
