# Generated by Django 2.0.2 on 2019-02-15 15:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0029_auto_20181103_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2019, 2, 15, 15, 38, 31, 268282, tzinfo=utc)),
        ),
    ]
