# Generated by Django 2.0.2 on 2019-02-15 16:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0030_auto_20190215_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2019, 2, 15, 16, 1, 18, 181114, tzinfo=utc)),
        ),
    ]
