# Generated by Django 2.0.5 on 2018-10-19 13:33

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20181019_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='content',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 19, 13, 33, 4, 43486), verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='content',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 19, 13, 33, 4, 43569), verbose_name='Date Update'),
        ),
    ]
