# Generated by Django 2.0.5 on 2018-10-25 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0045_auto_20181025_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 25, 17, 9, 59, 900968), verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='content',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 25, 17, 9, 59, 901037), verbose_name='Date Update'),
        ),
    ]
