# Generated by Django 2.0.5 on 2018-10-28 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0049_auto_20181026_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 0, 18, 58, 775578), verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='content',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 0, 18, 58, 775648), verbose_name='Date Update'),
        ),
    ]
