# Generated by Django 2.0 on 2018-11-02 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0054_auto_20181028_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 3, 1, 9, 48, 169065), verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='content',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 3, 1, 9, 48, 169065), verbose_name='Date Update'),
        ),
    ]
