# Generated by Django 2.0 on 2018-11-02 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0055_auto_20181103_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 3, 1, 55, 27, 794075), verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='content',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 3, 1, 55, 27, 794075), verbose_name='Date Update'),
        ),
    ]
