# Generated by Django 2.0 on 2018-11-03 00:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0057_auto_20181103_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 3, 3, 32, 59, 205503), verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='content',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 3, 3, 32, 59, 205503), verbose_name='Date Update'),
        ),
    ]
