# Generated by Django 2.0 on 2018-11-03 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0058_auto_20181103_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 3, 4, 22, 37, 894438), verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='content',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 3, 4, 22, 37, 894938), verbose_name='Date Update'),
        ),
    ]
