# Generated by Django 2.0.2 on 2019-02-15 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0059_auto_20181103_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 15, 18, 38, 31, 272282), verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='content',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 15, 18, 38, 31, 272282), verbose_name='Date Update'),
        ),
    ]
